version: "3"

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "63799:6379"
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    depends_on:
      - redis
    ports:
      - "8083:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
